### ISSUE TITLE
Link to readability.com "dead"

### ISSUE THREAD

**Issue by fwolfst** [thoughtbot/guides#463] opened 2016-12-30 15:17 UTC
The link to "keep the code simple" in
https://github.com/thoughtbot/guides/tree/master/best-practices
is "dead" (proprietary service shut down, yay Freemium). No idea how to get the links back.

**Comment by iwz** [comment] 2016-12-30 16:29
Thanks for the report. This is a dupe of https://github.com/thoughtbot/guides/pull/454, closing

**Closed by iwz** 2016-12-30 16:29 UTC

**Comment by fwolfst** [comment] 2016-12-30 16:39
Sorry, checked other issues but apparently overlooked it?!
