### ISSUE TITLE
Keep the code simple link no longer working

### ISSUE THREAD

**Issue by softr8** [thoughtbot/guides#474] opened 2017-02-06 15:48 UTC
This link: https://github.com/thoughtbot/guides/blob/master/best-practices/README.md points to a readability link which is no longer available

**Comment by WaKeMaTTa** [comment] 2017-02-06 15:54
Are you sure?

**Comment by tysongach** [comment] 2017-02-06 15:55
Duplicate of https://github.com/thoughtbot/guides/issues/452.

**Closed by tysongach** 2017-02-06 15:55 UTC
